const usersPlanet: { [key: string]: string } = {
  "morecchioni@eleven-labs.com": "Donut Factory",
  "bremond@eleven-labs.com": "Donut Factory",
  "fpasquet@eleven-labs.com": "Donut Factory",
  "mgautron@eleven-labs.com": "Donut Factory",
  "cgorron@eleven-labs.com": "Donut Factory",
  "aallier@eleven-labs.com": "Donut Factory",
  "ydiouri@eleven-labs.com": "Donut Factory",
  "klabiedh@eleven-labs.com": "Donut Factory",
  "lpointurier@eleven-labs.com": "Donut Factory",
  "rdemellier@eleven-labs.com": "Donut Factory",
  "yboucquetot@eleven-labs.com": "Donut Factory",
  "lflorant@eleven-labs.com": "Donut Factory",
  "obrahimi@eleven-labs.com": "Donut Factory",
  "gthibault@eleven-labs.com": "Donut Factory",
  "dboetsch@eleven-labs.com": "Donut Factory",
  "dduval@eleven-labs.com": "Donut Factory",
  "mpeaudecerf@eleven-labs.com": "Donut Factory",
  "clovergne@eleven-labs.com": "Donut Factory",
  "sbessoudo@eleven-labs.com": "Donut Factory",
  "cvelosovieira@eleven-labs.com": "Donut Factory",
  "hboudi@eleven-labs.com": "Donut Factory",
  "alesaint@eleven-labs.com": "Donut Factory",
  "rboitier@eleven-labs.com": "Donut Factory",
  "kboisseleau@eleven-labs.com": "Donut Factory",
  "lbauchet@eleven-labs.com": "Donut Factory",
  "chugueny@eleven-labs.com": "Duck Invaders",
  "ysamadi@eleven-labs.com": "Duck Invaders",
  "tthuon@eleven-labs.com": "Duck Invaders",
  "glepoutre@eleven-labs.com": "Duck Invaders",
  "dfert@eleven-labs.com": "Duck Invaders",
  "rgraillon@eleven-labs.com": "Duck Invaders",
  "seinhorn@eleven-labs.com": "Duck Invaders",
  "tperdriau@eleven-labs.com": "Duck Invaders",
  "mcharron@eleven-labs.com": "Duck Invaders",
  "pbrenot@eleven-labs.com": "Duck Invaders",
  "plerouge@eleven-labs.com": "Duck Invaders",
  "skontomarkos@eleven-labs.com": "Duck Invaders",
  "alipuma@eleven-labs.com": "Duck Invaders",
  "gcunsolo@eleven-labs.com": "Duck Invaders",
  "lsauvage@eleven-labs.com": "Duck Invaders",
  "mgrisole@eleven-labs.com": "Duck Invaders",
  "jmuller@eleven-labs.com": "Duck Invaders",
  "gboutroux@eleven-labs.com": "Duck Invaders",
  "nkania@eleven-labs.com": "Duck Invaders",
  "esolom@eleven-labs.com": "Duck Invaders",
  "jdupuis@eleven-labs.com": "Duck Invaders",
  "scoulibaly@eleven-labs.com": "Duck Invaders",
  "ahoudaibi@eleven-labs.com": "Duck Invaders",
  "yhanchaoui@eleven-labs.com": "Raccoons of Asgard",
  "tozalp@eleven-labs.com": "Raccoons of Asgard",
  "mminasyan@eleven-labs.com": "Raccoons of Asgard",
  "ngrevin@eleven-labs.com": "Raccoons of Asgard",
  "ajacquemin@eleven-labs.com": "Raccoons of Asgard",
  "mjoseph-gehannin@eleven-labs.com": "Raccoons of Asgard",
  "Iregaibi@eleven-labs.com": "Raccoons of Asgard",
  "kdung@eleven-labs.com": "Raccoons of Asgard",
  "fbelet@eleven-labs.com": "Raccoons of Asgard",
  "gcanal@eleven-labs.com": "Raccoons of Asgard",
  "amoutte@eleven-labs.com": "Raccoons of Asgard",
  "jbernard@eleven-labs.com": "Raccoons of Asgard",
  "efinalteri@eleven-labs.com": "Raccoons of Asgard",
  "rmarchand@eleven-labs.com": "Raccoons of Asgard",
  "psin@eleven-labs.com": "Raccoons of Asgard",
  "cmenna@eleven-labs.com": "Raccoons of Asgard",
  "jtruong@eleven-labs.com": "Raccoons of Asgard",
  "cjaunasse@eleven-labs.com": "Raccoons of Asgard",
  "fmigeot@eleven-labs.com": "Raccoons of Asgard",
  "kcordier@eleven-labs.com": "Raccoons of Asgard",
  "mmotsch@eleven-labs.com": "Raccoons of Asgard",
  "mounalli@eleven-labs.com": "Raccoons of Asgard",
  "hmohamedmahmoud@eleven-labs.com": "Raccoons of Asgard",
  "dbouvier@eleven-labs.com": "Raccoons of Asgard",
  "ohassan@eleven-labs.com": "Raccoons of Asgard",
  "rbenatitallah@eleven-labs.com": "Raccoons of Asgard",
  "sthouvenel@eleven-labs.com": "Raccoons of Asgard",
  "ydavid@eleven-labs.com": "Raccoons of Asgard",
  "elemarchand@eleven-labs.com": "Schizo Cats",
  "afauquet@eleven-labs.com": "Schizo Cats",
  "aamara@eleven-labs.com": "Schizo Cats",
  "mchardenal@eleven-labs.com": "Schizo Cats",
  "rjardinet@eleven-labs.com": "Schizo Cats",
  "jdebandt@eleven-labs.com": "Schizo Cats",
  "aandre@eleven-labs.com": "Schizo Cats",
  "mlenglet@eleven-labs.com": "Schizo Cats",
  "cjoye@eleven-labs.com": "Schizo Cats",
  "tnaulin@eleven-labs.com": "Schizo Cats",
  "fverneuil@eleven-labs.com": "Schizo Cats",
  "axu@eleven-labs.com": "Schizo Cats",
  "jbberthet@eleven-labs.com": "Schizo Cats",
  "clemercier@eleven-labs.com": "Schizo Cats",
  "metrapani@eleven-labs.com": "Schizo Cats",
  "sdasilva@eleven-labs.com": "Schizo Cats",
  "arubal@eleven-labs.com": "Schizo Cats",
  "mallier@eleven-labs.com": "Schizo Cats",
  "yboillon@eleven-labs.com": "Schizo Cats",
  "bamar@eleven-labs.com": "Schizo Cats",
  "glanau@eleven-labs.com": "Schizo Cats",
  "jmoati@eleven-labs.com": "Schizo Cats",
  "jbciepka@eleven-labs.com": "Schizo Cats",
  "alamkadem@eleven-labs.com": "Schizo Cats",
  "yohannmartinez34@gmail.com": "Schizo Cats",
  "ymartinez@eleven-labs.com": "Schizo Cats",
};

export default usersPlanet;
